-- MySQL Script generated by MySQL Workbench
-- Sat Apr 26 21:56:28 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cinemaweb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cinemaweb` ;

-- -----------------------------------------------------
-- Schema cinemaweb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cinemaweb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `cinemaweb` ;

-- -----------------------------------------------------
-- Table `booking`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `booking` ;

CREATE TABLE IF NOT EXISTS `booking` (
  `booking_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(36) NOT NULL,
  `schedule_id` INT NOT NULL,
  `seat_id` INT NOT NULL,
  `price` DOUBLE NOT NULL,
  `booking_day` DATE NOT NULL,
  `fd_id` INT NULL DEFAULT NULL,
  `food_and_drink_id` INT NOT NULL,
  PRIMARY KEY (`booking_id`),
  INDEX `fk_booking_user_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_booking_schedule_idx` (`schedule_id` ASC) VISIBLE,
  INDEX `fk_booking_seat_idx` (`seat_id` ASC) VISIBLE,
  INDEX `fk_booking_foodanddrink_idx` (`fd_id` ASC) VISIBLE,
  CONSTRAINT `fk_booking_foodanddrink`
    FOREIGN KEY (`fd_id`)
    REFERENCES `food_and_drink` (`fd_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_booking_schedule`
    FOREIGN KEY (`schedule_id`)
    REFERENCES `schedule` (`schedule_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_booking_seat`
    FOREIGN KEY (`seat_id`)
    REFERENCES `seat` (`seat_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_booking_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `cinema`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cinema` ;

CREATE TABLE IF NOT EXISTS `cinema` (
  `cinema_id` INT NOT NULL AUTO_INCREMENT,
  `cinema_name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `cinema_address` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  PRIMARY KEY (`cinema_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `film`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `film` ;

CREATE TABLE IF NOT EXISTS `film` (
  `film_id` INT NOT NULL AUTO_INCREMENT,
  `film_name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `film_poster` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `film_genre` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `film_length` INT NOT NULL,
  `film_description` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `film_review` INT NULL DEFAULT NULL,
  PRIMARY KEY (`film_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `food_and_drink`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food_and_drink` ;

CREATE TABLE IF NOT EXISTS `food_and_drink` (
  `fd_id` INT NOT NULL AUTO_INCREMENT,
  `fd_name` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `room_id` INT NOT NULL,
  `fd_price` DOUBLE NOT NULL,
  PRIMARY KEY (`fd_id`),
  INDEX `fk_foodanddrink_room_idx` (`room_id` ASC) VISIBLE,
  CONSTRAINT `fk_foodanddrink_room`
    FOREIGN KEY (`room_id`)
    REFERENCES `room` (`room_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `invalidated_token`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invalidated_token` ;

CREATE TABLE IF NOT EXISTS `invalidated_token` (
  `id` VARCHAR(255) NOT NULL,
  `expiry_time` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `password_otp`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `password_otp` ;

CREATE TABLE IF NOT EXISTS `password_otp` (
  `otp` VARCHAR(36) NOT NULL,
  `expiry_time` DATETIME(6) NOT NULL,
  `user_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`otp`),
  INDEX `fk_password_otp_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_password_otp_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `permission` ;

CREATE TABLE IF NOT EXISTS `permission` (
  `name` VARCHAR(20) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `role` ;

CREATE TABLE IF NOT EXISTS `role` (
  `name` VARCHAR(20) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `role_permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `role_permissions` ;

CREATE TABLE IF NOT EXISTS `role_permissions` (
  `role_name` VARCHAR(20) NOT NULL,
  `permission_name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`role_name`, `permission_name`),
  INDEX `fk_role_has_permission_permission1_idx` (`permission_name` ASC) VISIBLE,
  INDEX `fk_role_has_permission_role1_idx` (`role_name` ASC) VISIBLE,
  CONSTRAINT `fk_role_has_permission_permission1`
    FOREIGN KEY (`permission_name`)
    REFERENCES `permission` (`name`),
  CONSTRAINT `fk_role_has_permission_role1`
    FOREIGN KEY (`role_name`)
    REFERENCES `role` (`name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `room`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `room` ;

CREATE TABLE IF NOT EXISTS `room` (
  `room_id` INT NOT NULL AUTO_INCREMENT,
  `cinema_id` INT NOT NULL,
  `room_name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`room_id`),
  INDEX `fk_room_cinema_idx` (`cinema_id` ASC) VISIBLE,
  CONSTRAINT `fk_room_cinema`
    FOREIGN KEY (`cinema_id`)
    REFERENCES `cinema` (`cinema_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `schedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schedule` ;

CREATE TABLE IF NOT EXISTS `schedule` (
  `schedule_id` INT NOT NULL AUTO_INCREMENT,
  `film_id` INT NOT NULL,
  `room_id` INT NOT NULL,
  `schedule_date` DATE NOT NULL,
  `schedule_start` TIME NOT NULL,
  `schedule_end` TIME NOT NULL,
  PRIMARY KEY (`schedule_id`),
  INDEX `fk_schedule_room_idx` (`room_id` ASC) VISIBLE,
  INDEX `fk_schedule_film_idx` (`film_id` ASC) VISIBLE,
  CONSTRAINT `fk_schedule_film`
    FOREIGN KEY (`film_id`)
    REFERENCES `film` (`film_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_schedule_room`
    FOREIGN KEY (`room_id`)
    REFERENCES `room` (`room_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `seat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seat` ;

CREATE TABLE IF NOT EXISTS `seat` (
  `seat_id` INT NOT NULL AUTO_INCREMENT,
  `seat_type` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `room_id` INT NOT NULL,
  `row` VARCHAR(10) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `number` INT NOT NULL,
  `seat_price` DOUBLE NOT NULL,
  PRIMARY KEY (`seat_id`),
  INDEX `fk_seat_room_idx` (`room_id` ASC) VISIBLE,
  CONSTRAINT `fk_seat_room`
    FOREIGN KEY (`room_id`)
    REFERENCES `room` (`room_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user` ;

CREATE TABLE IF NOT EXISTS `user` (
  `user_id` VARCHAR(36) NOT NULL,
  `username` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `password` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `first_name` VARCHAR(20) NOT NULL,
  `last_name` VARCHAR(20) NOT NULL,
  `date_of_birth` DATE NOT NULL,
  `gender` TINYINT NOT NULL,
  `avatar` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `email` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `phone_number` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `point` DOUBLE NULL DEFAULT '0',
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `user_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user_roles` ;

CREATE TABLE IF NOT EXISTS `user_roles` (
  `user_id` VARCHAR(36) NOT NULL,
  `role_name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`user_id`, `role_name`),
  INDEX `fk_user_has_role_role1_idx` (`role_name` ASC) VISIBLE,
  INDEX `fk_user_has_role_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_role_role1`
    FOREIGN KEY (`role_name`)
    REFERENCES `role` (`name`),
  CONSTRAINT `fk_user_has_role_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
