server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: "jdbc:mysql://localhost:3307/cinemaweb?serverTimezone=Asia/Ho_Chi_Minh"
    username: root
    password: Daolelongvu2005@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  spring:
    jackson:
      date-format: yyyy-MM-dd
      time-format: HH:mm:ss