server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cinemaweb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: phuong4404
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "fAhsFQLtyhPPawzKmGDEU/IDeBpV7nGnIaQIWYZCzh8qGSb+ETsbFOoMfwfNsUgA"

