server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: "jdbc:mysql://localhost:3307/cinemaweb"
    username: root
    password: Daolelongvu2005@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true