server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: "jdbc:mysql://localhost:3307/cinemaweb?serverTimezone=Asia/Ho_Chi_Minh"
    username: root
    password: phuong4404
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: buihaiphupng6@gmail.com
    password: mdfabuwjbybeuaal
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com
  spring:
    jackson:
      date-format: yyyy-MM-dd
      time-format: HH:mm:ss

jwt:
  signerKey: "fAhsFQLtyhPPawzKmGDEU/IDeBpV7nGnIaQIWYZCzh8qGSb+ETsbFOoMfwfNsUgA"